services:
  mgraph_ai_serverless:
    build:
      context: ../../..
      dockerfile: ./deploy/docker/mgraph-ai-serverless/Dockerfile
    platform: linux/amd64
    container_name: mgraph_ai_serverless
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../../../mgraph_ai_serverless:/app/mgraph_ai_serverless
    env_file:
      - ../../../.env
